
/**
 * Interface for the data sent TO the backend /api/query endpoint.
 */
export interface ApiQueryRequest {
    user_query: string;
  }
  
  /**
   * Interface for the data received FROM the backend /api/query endpoint on success.
   */
  export interface ApiQueryResponse {
    user_query: string;        // The original query sent by the user
    generated_sql: string;     // The SQL query generated by the backend
    response: string;          // The natural language response generated by the backend
    columns: string[];         // An array of column names for the results table
    results: any[][];          // The actual query results as an array of arrays.
                               // Each inner array represents a row, and its elements correspond
                               // to the columns defined in the 'columns' array.
                               // Using 'any[][]' as database types can vary. You could potentially
                               // make this more specific if you knew the exact possible types.
  }
  
  /**
   * Optional: Interface for a potential error response structure.
   * Adapt this based on how you consistently return errors from Flask.
   */
  export interface ApiErrorResponse {
    error: string;
  }